[package]
name = "eisel-lemire"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
num-bigint = "0.4.3"
num-traits = "0.2.14"

[dev-dependencies]
num-bigint = "0.4.3"

[dependencies]